---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Pihub:
        href: http://192.168.1.176:3000
        description: Raspberry Pi infrastructure hub
    - Uptime Kuma:
        href: https://uptime.melolab.dev
        description: Uptime monitoring
    - Pi-hole:
        href: https://pihole.melolab.dev/admin
        description: DNS and ad blocking
