services:
  service-name:
    image:
    container_name:

    restart: unless-stopped

    env_file:
      - ../.env

    environment:

    ports:

    volumes:

    depends_on:

    networks:
      - pihub
