services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    volumes:
      - ../runtime/uptime-kuma/data:/app/data
    networks:
      - pihub
