services:
  webterm:
    build: ../services/webterm
    image: melolab/webterm:latest
    container_name: webterm
    restart: unless-stopped
    ports:
      - "8091:8091"
    environment:
      SSH_KEY: "/key"
      TARGETS_PATH: "/targets.json"
      INDEX_PATH: "/www/index.html"
    volumes:
      - ../runtime/webterm/key:/key:ro
      - ../services/webterm/index.html:/www/index.html:ro
      - ../services/webterm/targets.json:/targets.json:ro
    networks:
      - pihub
